name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Add dummy test script if missing
      run: |
        node -e "const fs = require('fs'); let pkg = JSON.parse(fs.readFileSync('package.json')); pkg.scripts = pkg.scripts || {}; if (!pkg.scripts.test) { pkg.scripts.test = 'echo No tests defined && exit 0'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2)); }"

    - name: Run tests
      run: npm test
